(function(){
  const languages={en:{name:'English',path:'/'},hi:{name:'हिन्दी',path:'/hi/'},tr:{name:'Türkçe',path:'/tr/'},vi:{name:'Tiếng Việt',path:'/vi/'},es:{name:'Español',path:'/es/'},ru:{name:'Русский',path:'/ru/'},id:{name:'Bahasa Indonesia',path:'/id/'},de:{name:'Deutsch',path:'/de/'},fr:{name:'Français',path:'/fr/'}};
  const codes=Object.keys(languages);
  function current(){const p=location.pathname.replace(/\/+$/,'')||'/';return codes.find(c=>languages[c].path.replace(/\/+$/,'')===p)||'en'}
  function detect(){const n=(navigator.language||'en').toLowerCase();if(/-in$/.test(n))return'en';if(/^hi(?:-|$)/.test(n))return'hi';if(/^tr(?:-|$)/.test(n))return'tr';if(/^vi(?:-|$)/.test(n))return'vi';if(/^es(?:-|$)/.test(n))return'es';if(/^ru(?:-|$)/.test(n))return'ru';if(/^id(?:-|$)/.test(n))return'id';if(/^de(?:-|$)/.test(n))return'de';if(/^fr(?:-|$)/.test(n))return'fr';return'en'}
  const texts={en:['Choose your language','Select a language for the best experience.','Continue','Language detected from your browser'],hi:['अपनी भाषा चुनें','बेहतरीन अनुभव के लिए एक भाषा चुनें।','जारी रखें','भाषा आपके ब्राउज़र से पहचानी गई'],tr:['Dilinizi seçin','En iyi deneyim için bir dil seçin.','Devam','Dil tarayıcınızdan algılandı'],vi:['Chọn ngôn ngữ','Chọn ngôn ngữ để có trải nghiệm tốt nhất.','Tiếp tục','Ngôn ngữ được nhận diện từ trình duyệt'],es:['Elige tu idioma','Selecciona un idioma para disfrutar de la mejor experiencia.','Continuar','Idioma detectado desde tu navegador'],ru:['Выберите язык','Выберите язык для лучшего опыта.','Продолжить','Язык определён браузером'],id:['Pilih bahasa Anda','Pilih bahasa untuk pengalaman terbaik.','Lanjutkan','Bahasa terdeteksi dari browser'],de:['Sprache auswählen','Wähle eine Sprache für die beste Erfahrung.','Weiter','Sprache aus deinem Browser erkannt'],fr:['Choisissez votre langue','Sélectionnez une langue pour une meilleure expérience.','Continuer','Langue détectée par votre navigateur']};
  const seo={
    en:{title:'MANAV SOLS | Website Developer & Digital Solutions',description:'Website developer and website designer for businesses, professionals and startups. Affordable website development, custom web design, software and automation by MANAV SOLS.',keywords:['website developer','website designer','web development services','website design services','affordable website development','affordable website designer','business website developer','professional website designer','custom website development','responsive website designer','web designer for small business','custom software development','AI automation services','Delhi website developer','Gurugram website developer','Noida website designer','Mumbai website developer','Bengaluru website designer','Hyderabad website developer','Pune website designer','Chennai website developer','Dubai website developer','Singapore website developer','London website designer','Toronto website developer','Sydney website designer','San Francisco website developer','New York website designer']},
    hi:{title:'MANAV SOLS | वेबसाइट डेवलपर और डिजिटल सॉल्यूशंस',description:'बिज़नेस, प्रोफेशनल्स और स्टार्टअप्स के लिए वेबसाइट डेवलपर और वेबसाइट डिजाइनर। किफायती वेबसाइट डेवलपमेंट, कस्टम वेब डिजाइन, सॉफ्टवेयर और ऑटोमेशन सेवाएँ।',keywords:['वेबसाइट डेवलपर','वेबसाइट डिजाइनर','वेब डेवलपमेंट सेवाएँ','वेबसाइट डिजाइन सेवाएँ','किफायती वेबसाइट डेवलपमेंट','किफायती वेबसाइट डिजाइनर','बिज़नेस वेबसाइट डेवलपर','प्रोफेशनल वेबसाइट डिजाइनर','कस्टम वेबसाइट डेवलपमेंट','रिस्पॉन्सिव वेबसाइट डिजाइनर','दिल्ली वेबसाइट डेवलपर','गुरुग्राम वेबसाइट डेवलपर','नोएडा वेबसाइट डिजाइनर','मुंबई वेबसाइट डेवलपर','बेंगलुरु वेबसाइट डिजाइनर','हैदराबाद वेबसाइट डेवलपर','पुणे वेबसाइट डिजाइनर','चेन्नई वेबसाइट डेवलपर']},
    tr:{title:'MANAV SOLS | Web Geliştirici ve Dijital Çözümler',description:'İşletmeler, profesyoneller ve girişimler için web geliştirici ve web tasarım hizmetleri. Uygun fiyatlı web sitesi geliştirme, özel tasarım, yazılım ve otomasyon.',keywords:['web geliştirici','web tasarımcı','web geliştirme hizmetleri','web sitesi tasarımı','uygun fiyatlı web sitesi','profesyonel web tasarım','işletme web sitesi','özel web geliştirme','duyarlı web tasarım','Delhi web geliştirici','Gurugram web geliştirici','Noida web tasarımcı','Mumbai web geliştirici','Bengaluru web tasarımcı','Dubai web geliştirici','Singapur web geliştirici','Londra web tasarımcı']},
    vi:{title:'MANAV SOLS | Lập trình viên Website & Giải pháp số',description:'Dịch vụ phát triển và thiết kế website cho doanh nghiệp, chuyên gia và startup. Website giá hợp lý, thiết kế tùy chỉnh, phần mềm và tự động hóa.',keywords:['lập trình viên website','thiết kế website','dịch vụ phát triển website','dịch vụ thiết kế website','website giá hợp lý','thiết kế web chuyên nghiệp','website doanh nghiệp','phát triển web tùy chỉnh','thiết kế responsive','website developer Hanoi','website designer Ho Chi Minh City','website developer Da Nang','website designer Singapore','website developer Dubai']},
    es:{title:'MANAV SOLS | Desarrollador Web y Soluciones Digitales',description:'Desarrollador y diseñador web para empresas, profesionales y startups. Desarrollo web asequible, diseño personalizado, software y automatización.',keywords:['desarrollador web','diseñador web','servicios de desarrollo web','diseño de sitios web','desarrollo web asequible','diseñador web profesional','sitio web para empresas','desarrollo web personalizado','diseño web responsive','desarrollador web Madrid','diseñador web Barcelona','desarrollador web México','diseñador web Bogotá','desarrollador web Miami']},
    ru:{title:'MANAV SOLS | Веб-разработчик и цифровые решения',description:'Веб-разработчик и веб-дизайнер для бизнеса, специалистов и стартапов. Доступная разработка сайтов, индивидуальный дизайн, программное обеспечение и автоматизация.',keywords:['веб-разработчик','веб-дизайнер','разработка сайтов','дизайн сайтов','доступная разработка сайтов','профессиональный веб-дизайнер','сайт для бизнеса','индивидуальная веб-разработка','адаптивный веб-дизайн','веб-разработчик Москва','веб-дизайнер Санкт-Петербург','веб-разработчик Dubai','веб-дизайнер London']},
    id:{title:'MANAV SOLS | Pengembang Website & Solusi Digital',description:'Pengembang dan desainer website untuk bisnis, profesional, dan startup. Pengembangan website terjangkau, desain khusus, software, dan otomasi.',keywords:['pengembang website','desainer website','jasa pengembangan website','jasa desain website','website terjangkau','desainer web profesional','website bisnis','pengembangan web kustom','desain responsive','pengembang website Jakarta','desainer website Bandung','pengembang website Bali','pengembang website Singapore','pengembang website Dubai']},
    de:{title:'MANAV SOLS | Webentwickler & Digitale Lösungen',description:'Webentwickler und Webdesigner für Unternehmen, Fachleute und Startups. Günstige Webentwicklung, individuelles Design, Software und Automatisierung.',keywords:['Webentwickler','Webdesigner','Webentwicklung','Website Design','günstige Webentwicklung','professioneller Webdesigner','Business Website Entwickler','individuelle Webentwicklung','responsive Webdesign','Webentwickler Berlin','Webdesigner München','Webentwickler Frankfurt','Webentwickler Dubai','Webdesigner London']},
    fr:{title:'MANAV SOLS | Développeur Web & Solutions Numériques',description:'Développeur et designer web pour entreprises, professionnels et startups. Création de sites web abordable, design personnalisé, logiciels et automatisation.',keywords:['développeur web','designer web','services de développement web','conception de site web','création de site web abordable','designer web professionnel','site web entreprise','développement web personnalisé','design responsive','développeur web Paris','designer web Lyon','développeur web Montréal','développeur web Dubai','designer web Londres']}
  };
  function meta(name,content,property){let el=document.head.querySelector(property?`meta[property="${name}"]`:`meta[name="${name}"]`);if(!el){el=document.createElement('meta');(property?el.setAttribute('property',name):el.setAttribute('name',name));document.head.appendChild(el)}el.setAttribute('content',content)}
  function applySeo(code){const s=seo[code]||seo.en;document.title=s.title;meta('description',s.description);meta('keywords',s.keywords.join(', '));meta('author','MANAV SOLS');meta('robots','index, follow');meta('og:title',s.title,true);meta('og:description',s.description,true);meta('og:type','website',true);meta('og:url',location.href.split('#')[0],true);meta('og:site_name','MANAV SOLS',true);meta('twitter:card','summary');meta('twitter:title',s.title);meta('twitter:description',s.description);}
  function addTermsLink(){
    const footer=document.querySelector('footer');
    if(!footer)return;
    const existing=footer.querySelector('a[href="/terms/"]');
    if(existing)return;
    let line=footer.querySelector('.footer-link');
    if(!line){line=document.createElement('p');line.className='footer-link';footer.appendChild(line)}
    const link=document.createElement('a');link.href='/terms/';link.textContent='Terms & Conditions';
    if(line.textContent.trim())line.appendChild(document.createTextNode(' · '));
    line.appendChild(link);
  }
  function add(){const nav=document.querySelector('.navbar');if(!nav)return;if(!document.getElementById('languageBtn')){const tools=document.createElement('div');tools.className='language-tools';tools.innerHTML='<button class="language-button" id="languageBtn" type="button" aria-haspopup="dialog" aria-controls="languageModal" aria-label="Change language"><i class="fa-solid fa-globe" aria-hidden="true"></i><span id="currentLanguageLabel">English</span></button>';nav.appendChild(tools)}if(!document.getElementById('languageModal')){const modal=document.createElement('div');modal.className='language-modal';modal.id='languageModal';modal.setAttribute('aria-hidden','true');modal.innerHTML='<div class="language-backdrop" data-close-language></div><div class="language-dialog" role="dialog" aria-modal="true" aria-labelledby="languageTitle"><button class="language-close" id="languageClose" type="button" aria-label="Close language selector">×</button><div class="language-icon"><i class="fa-solid fa-language" aria-hidden="true"></i></div><h2 id="languageTitle">Choose your language</h2><p id="languageSubtitle">Select a language for the best experience.</p><select id="languageSelect" aria-label="Select language"></select><button class="btn primary language-continue" id="languageContinue" type="button">Continue</button><p class="language-detected" id="languageDetected"></p></div></div>';document.body.appendChild(modal)}}
  function go(code){localStorage.setItem('manavsols-language',code);localStorage.setItem('manavsols-language-selected','1');location.href=languages[code].path}
  function setup(){add();const code=current(),saved=localStorage.getItem('manavsols-language');const suggested=saved&&languages[saved]?saved:detect();if(code==='en'&&/-in$/.test((navigator.language||'').toLowerCase()))localStorage.setItem('manavsols-language','en');
    const btn=document.getElementById('languageBtn'),label=document.getElementById('currentLanguageLabel'),modal=document.getElementById('languageModal'),sel=document.getElementById('languageSelect'),close=document.getElementById('languageClose'),cont=document.getElementById('languageContinue'),det=document.getElementById('languageDetected');if(label)label.textContent=languages[code].name;if(sel){sel.innerHTML=codes.map(c=>`<option value="${c}">${languages[c].name}</option>`).join('');sel.value=code}
    function paint(c){const t=texts[c]||texts.en;document.getElementById('languageTitle').textContent=t[0];document.getElementById('languageSubtitle').textContent=t[1];cont.textContent=t[2]}
    function closeModal(){modal.classList.remove('open');modal.setAttribute('aria-hidden','true');document.body.classList.remove('language-open')}
    function openModal(initial){modal.classList.add('open');modal.setAttribute('aria-hidden','false');document.body.classList.add('language-open');sel.value=initial||code;paint(sel.value);if(det&&initial)det.textContent=(texts[sel.value]||texts.en)[3]+': '+languages[sel.value].name}
    if(btn)btn.onclick=()=>openModal(code);if(close)close.onclick=closeModal;if(cont)cont.onclick=()=>go(sel.value);if(sel)sel.onchange=()=>paint(sel.value);document.querySelectorAll('[data-close-language]').forEach(e=>e.onclick=closeModal);document.onkeydown=e=>{if(e.key==='Escape')closeModal()};
    applySeo(code);addTermsLink();
    if(!localStorage.getItem('manavsols-language-selected'))setTimeout(()=>openModal(suggested),450);
  }
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',setup);else setup();
})();