(function(){
  const languages={en:{name:'English',path:'/'},hi:{name:'हिन्दी',path:'/hi/'},tr:{name:'Türkçe',path:'/tr/'},vi:{name:'Tiếng Việt',path:'/vi/'},es:{name:'Español',path:'/es/'},ru:{name:'Русский',path:'/ru/'},id:{name:'Bahasa Indonesia',path:'/id/'},de:{name:'Deutsch',path:'/de/'},fr:{name:'Français',path:'/fr/'}};
  const codes=Object.keys(languages);
  const locales={en:'en_IN',hi:'hi_IN',tr:'tr_TR',vi:'vi_VN',es:'es_ES',ru:'ru_RU',id:'id_ID',de:'de_DE',fr:'fr_FR'};
  function current(){const p=location.pathname.replace(/\/+$/,'')||'/';return codes.find(c=>languages[c].path.replace(/\/+$/,'')===p)||'en'}
  function detect(){const n=(navigator.language||'en').toLowerCase();if(/-in$/.test(n))return'en';if(/^hi(?:-|$)/.test(n))return'hi';if(/^tr(?:-|$)/.test(n))return'tr';if(/^vi(?:-|$)/.test(n))return'vi';if(/^es(?:-|$)/.test(n))return'es';if(/^ru(?:-|$)/.test(n))return'ru';if(/^id(?:-|$)/.test(n))return'id';if(/^de(?:-|$)/.test(n))return'de';if(/^fr(?:-|$)/.test(n))return'fr';return'en'}
  const texts={en:['Choose your language','Select a language for the best experience.','Continue','Language detected from your browser'],hi:['अपनी भाषा चुनें','बेहतरीन अनुभव के लिए एक भाषा चुनें।','जारी रखें','भाषा आपके ब्राउज़र से पहचानी गई'],tr:['Dilinizi seçin','En iyi deneyim için bir dil seçin.','Devam','Dil tarayıcınızdan algılandı'],vi:['Chọn ngôn ngữ','Chọn ngôn ngữ để có trải nghiệm tốt nhất.','Tiếp tục','Ngôn ngữ được nhận diện từ trình duyệt'],es:['Elige tu idioma','Selecciona un idioma para disfrutar de la mejor experiencia.','Continuar','Idioma detectado desde tu navegador'],ru:['Выберите язык','Выберите язык для лучшего опыта.','Продолжить','Язык определён браузером'],id:['Pilih bahasa Anda','Pilih bahasa untuk pengalaman terbaik.','Lanjutkan','Bahasa terdeteksi dari browser'],de:['Sprache auswählen','Wähle eine Sprache für die beste Erfahrung.','Weiter','Sprache aus deinem Browser erkannt'],fr:['Choisissez votre langue','Sélectionnez une langue pour une meilleure expérience.','Continuer','Langue détectée par votre navigateur']};
  const seo={
    en:{title:'MANAV SOLS | Website Development & Web Design Services',description:'Professional website developer and web designer for businesses, professionals and startups. Affordable website development, custom web design, software and automation by MANAV SOLS.',keywords:['website developer','website designer','website development services','website design services','website maker','affordable website development','affordable website designer','affordable website maker','business website developer','small business website designer','professional website designer','custom website development','custom web design','responsive website designer','freelance web developer','web development company','website design company','custom software development','AI automation services','Delhi website developer','Delhi NCR website designer','Gurugram website developer','Noida website designer','Mumbai website developer','Bengaluru website designer','Hyderabad website developer','Pune website designer','Chennai website developer','Dubai website developer','Singapore website designer','London website developer','Toronto website designer','Sydney website developer','New York website designer']},
    hi:{title:'MANAV SOLS | वेबसाइट डेवलपर, डिजाइनर और डिजिटल सॉल्यूशंस',description:'बिज़नेस, प्रोफेशनल्स और स्टार्टअप्स के लिए वेबसाइट डेवलपर और वेबसाइट डिजाइनर। किफायती वेबसाइट डेवलपमेंट, कस्टम वेब डिजाइन, सॉफ्टवेयर और ऑटोमेशन सेवाएँ।',keywords:['वेबसाइट डेवलपर','वेबसाइट डिजाइनर','वेबसाइट डेवलपमेंट सेवाएँ','वेबसाइट डिजाइन सेवाएँ','वेबसाइट मेकर','किफायती वेबसाइट डेवलपमेंट','किफायती वेबसाइट डिजाइनर','किफायती वेबसाइट मेकर','बिज़नेस वेबसाइट डेवलपर','छोटे बिज़नेस वेबसाइट डिजाइनर','प्रोफेशनल वेबसाइट डिजाइनर','कस्टम वेबसाइट डेवलपमेंट','कस्टम वेब डिजाइन','रिस्पॉन्सिव वेबसाइट डिजाइनर','वेब डेवलपमेंट कंपनी','वेबसाइट डिजाइन कंपनी','कस्टम सॉफ्टवेयर डेवलपमेंट','AI ऑटोमेशन सेवाएँ','दिल्ली वेबसाइट डेवलपर','दिल्ली NCR वेबसाइट डिजाइनर','गुरुग्राम वेबसाइट डेवलपर','नोएडा वेबसाइट डिजाइनर','मुंबई वेबसाइट डेवलपर','बेंगलुरु वेबसाइट डिजाइनर','हैदराबाद वेबसाइट डेवलपर','पुणे वेबसाइट डिजाइनर','चेन्नई वेबसाइट डेवलपर']},
    tr:{title:'MANAV SOLS | Web Geliştirme ve Web Tasarım Hizmetleri',description:'İşletmeler, profesyoneller ve girişimler için web geliştirici ve web tasarım hizmetleri. Uygun fiyatlı web sitesi, özel tasarım, yazılım ve otomasyon çözümleri.',keywords:['web geliştirici','web tasarımcı','web geliştirme hizmetleri','web sitesi tasarımı','web sitesi yapımcısı','uygun fiyatlı web sitesi geliştirme','uygun fiyatlı web tasarımcı','işletme web sitesi','küçük işletme web tasarımı','profesyonel web tasarım','özel web geliştirme','özel web tasarımı','responsive web tasarım','web geliştirme şirketi','web tasarım şirketi','özel yazılım geliştirme','AI otomasyon hizmetleri','Delhi web geliştirici','Gurugram web geliştirici','Noida web tasarımcı','Mumbai web geliştirici','Bengaluru web tasarımcı','Dubai web geliştirici','Singapur web tasarımcı','Londra web geliştirici']},
    vi:{title:'MANAV SOLS | Phát triển Website & Thiết kế Web',description:'Dịch vụ phát triển và thiết kế website cho doanh nghiệp, chuyên gia và startup. Website giá hợp lý, thiết kế tùy chỉnh, phần mềm và tự động hóa bởi MANAV SOLS.',keywords:['lập trình viên website','thiết kế website','dịch vụ phát triển website','dịch vụ thiết kế website','người làm website','phát triển website giá hợp lý','thiết kế website giá hợp lý','website doanh nghiệp','thiết kế website cho doanh nghiệp nhỏ','thiết kế web chuyên nghiệp','phát triển web tùy chỉnh','thiết kế web tùy chỉnh','thiết kế responsive','công ty phát triển web','công ty thiết kế website','phát triển phần mềm tùy chỉnh','dịch vụ AI và tự động hóa','lập trình viên website Hà Nội','thiết kế website Thành phố Hồ Chí Minh','lập trình viên website Đà Nẵng','thiết kế website Singapore','lập trình viên website Dubai']},
    es:{title:'MANAV SOLS | Desarrollo Web y Diseño de Sitios',description:'Desarrollador y diseñador web para empresas, profesionales y startups. Desarrollo web asequible, diseño personalizado, software y automatización con MANAV SOLS.',keywords:['desarrollador web','diseñador web','servicios de desarrollo web','diseño de sitios web','creador de sitios web','desarrollo web asequible','diseñador web asequible','sitio web para empresas','diseño web para pequeñas empresas','diseñador web profesional','desarrollo web personalizado','diseño web personalizado','diseño responsive','empresa de desarrollo web','empresa de diseño web','desarrollo de software personalizado','servicios de IA y automatización','desarrollador web Madrid','diseñador web Barcelona','desarrollador web México','diseñador web Bogotá','desarrollador web Miami']},
    ru:{title:'MANAV SOLS | Веб-разработка и дизайн сайтов',description:'Веб-разработчик и веб-дизайнер для бизнеса, специалистов и стартапов. Доступная разработка сайтов, индивидуальный дизайн, ПО и автоматизация от MANAV SOLS.',keywords:['веб-разработчик','веб-дизайнер','разработка сайтов','дизайн сайтов','создание сайтов','доступная разработка сайтов','доступный веб-дизайнер','сайт для бизнеса','сайт для малого бизнеса','профессиональный веб-дизайнер','индивидуальная веб-разработка','индивидуальный веб-дизайн','адаптивный веб-дизайн','компания веб-разработки','компания веб-дизайна','разработка ПО','AI и автоматизация','веб-разработчик Москва','веб-дизайнер Санкт-Петербург','веб-разработчик Dubai','веб-дизайнер London']},
    id:{title:'MANAV SOLS | Pengembangan Website & Desain Web',description:'Pengembang dan desainer website untuk bisnis, profesional, dan startup. Pengembangan website terjangkau, desain khusus, software, dan otomasi oleh MANAV SOLS.',keywords:['pengembang website','desainer website','jasa pengembangan website','jasa desain website','pembuat website','pengembangan website terjangkau','desainer website terjangkau','website bisnis','desain website untuk bisnis kecil','desainer web profesional','pengembangan web kustom','desain web kustom','desain responsive','perusahaan pengembangan web','perusahaan desain website','pengembangan software kustom','layanan AI dan otomasi','pengembang website Jakarta','desainer website Bandung','pengembang website Bali','pengembang website Singapore','pengembang website Dubai']},
    de:{title:'MANAV SOLS | Webentwicklung & Webdesign Services',description:'Webentwickler und Webdesigner für Unternehmen, Fachleute und Startups. Günstige Webentwicklung, individuelles Design, Software und Automatisierung von MANAV SOLS.',keywords:['Webentwickler','Webdesigner','Webentwicklung','Website Design','Website-Ersteller','günstige Webentwicklung','günstiger Webdesigner','Business-Website-Entwickler','Website für kleine Unternehmen','professioneller Webdesigner','individuelle Webentwicklung','individuelles Webdesign','responsive Webdesign','Webentwicklungsunternehmen','Webdesign-Unternehmen','individuelle Softwareentwicklung','KI und Automatisierung','Webentwickler Berlin','Webdesigner München','Webentwickler Frankfurt','Webentwickler Dubai','Webdesigner London']},
    fr:{title:'MANAV SOLS | Développement Web & Design de Sites',description:'Développeur et designer web pour entreprises, professionnels et startups. Création de sites abordable, design personnalisé, logiciels et automatisation par MANAV SOLS.',keywords:['développeur web','designer web','services de développement web','conception de site web','créateur de site web','création de site web abordable','designer web abordable','site web entreprise','site web pour petite entreprise','designer web professionnel','développement web personnalisé','design web personnalisé','design responsive','entreprise de développement web','entreprise de design web','développement logiciel personnalisé','services IA et automatisation','développeur web Paris','designer web Lyon','développeur web Montréal','développeur web Dubai','designer web Londres']}
  };
  const contactLabels={
    en:{call:'Call',whatsapp:'WhatsApp',email:'Email',linkedin:'LinkedIn',github:'GitHub',instagram:'Instagram',youtube:'YouTube',channel:'WhatsApp Channel',founder:'Founder Profile',projects:'MANAV SOLS Projects',brand:'MANAV SOLS',content:'MANAV SOLS Content',updates:'MANAV SOLS Updates'},
    hi:{call:'कॉल',whatsapp:'WhatsApp',email:'ईमेल',linkedin:'LinkedIn',github:'GitHub',instagram:'Instagram',youtube:'YouTube',channel:'WhatsApp Channel',founder:'संस्थापक प्रोफ़ाइल',projects:'MANAV SOLS प्रोजेक्ट्स',brand:'MANAV SOLS',content:'MANAV SOLS कंटेंट',updates:'MANAV SOLS अपडेट्स'},
    tr:{call:'Ara',whatsapp:'WhatsApp',email:'E-posta',linkedin:'LinkedIn',github:'GitHub',instagram:'Instagram',youtube:'YouTube',channel:'WhatsApp Kanalı',founder:'Kurucu Profili',projects:'MANAV SOLS Projeleri',brand:'MANAV SOLS',content:'MANAV SOLS İçerikleri',updates:'MANAV SOLS Güncellemeleri'},
    vi:{call:'Gọi điện',whatsapp:'WhatsApp',email:'Email',linkedin:'LinkedIn',github:'GitHub',instagram:'Instagram',youtube:'YouTube',channel:'Kênh WhatsApp',founder:'Hồ sơ nhà sáng lập',projects:'Dự án MANAV SOLS',brand:'MANAV SOLS',content:'Nội dung MANAV SOLS',updates:'Cập nhật MANAV SOLS'},
    es:{call:'Llamar',whatsapp:'WhatsApp',email:'Email',linkedin:'LinkedIn',github:'GitHub',instagram:'Instagram',youtube:'YouTube',channel:'Canal de WhatsApp',founder:'Perfil del fundador',projects:'Proyectos MANAV SOLS',brand:'MANAV SOLS',content:'Contenido MANAV SOLS',updates:'Actualizaciones MANAV SOLS'},
    ru:{call:'Позвонить',whatsapp:'WhatsApp',email:'Почта',linkedin:'LinkedIn',github:'GitHub',instagram:'Instagram',youtube:'YouTube',channel:'Канал WhatsApp',founder:'Профиль основателя',projects:'Проекты MANAV SOLS',brand:'MANAV SOLS',content:'Контент MANAV SOLS',updates:'Обновления MANAV SOLS'},
    id:{call:'Telepon',whatsapp:'WhatsApp',email:'Email',linkedin:'LinkedIn',github:'GitHub',instagram:'Instagram',youtube:'YouTube',channel:'Saluran WhatsApp',founder:'Profil Pendiri',projects:'Proyek MANAV SOLS',brand:'MANAV SOLS',content:'Konten MANAV SOLS',updates:'Pembaruan MANAV SOLS'},
    de:{call:'Anrufen',whatsapp:'WhatsApp',email:'E-Mail',linkedin:'LinkedIn',github:'GitHub',instagram:'Instagram',youtube:'YouTube',channel:'WhatsApp-Kanal',founder:'Gründerprofil',projects:'MANAV SOLS Projekte',brand:'MANAV SOLS',content:'MANAV SOLS Inhalte',updates:'MANAV SOLS Updates'},
    fr:{call:'Appeler',whatsapp:'WhatsApp',email:'Email',linkedin:'LinkedIn',github:'GitHub',instagram:'Instagram',youtube:'YouTube',channel:'Chaîne WhatsApp',founder:'Profil du fondateur',projects:'Projets MANAV SOLS',brand:'MANAV SOLS',content:'Contenu MANAV SOLS',updates:'Mises à jour MANAV SOLS'}
  };
  function meta(name,content,property){let el=document.head.querySelector(property?`meta[property="${name}"]`:`meta[name="${name}"]`);if(!el){el=document.createElement('meta');(property?el.setAttribute('property',name):el.setAttribute('name',name));document.head.appendChild(el)}el.setAttribute('content',content)}
  function applySeo(code){const s=seo[code]||seo.en;const url=`${location.origin}${languages[code].path}`;document.documentElement.lang=code==='en'?'en-IN':code;document.title=s.title;meta('description',s.description);meta('keywords',s.keywords.join(', '));meta('author','MANAV SOLS');meta('robots','index, follow, max-image-preview:large, max-snippet:-1, max-video-preview:-1');meta('og:title',s.title,true);meta('og:description',s.description,true);meta('og:type','website',true);meta('og:url',url,true);meta('og:site_name','MANAV SOLS',true);meta('og:locale',locales[code]||'en_IN',true);meta('twitter:card','summary');meta('twitter:title',s.title);meta('twitter:description',s.description)}
  function syncContactCards(code){
    const grid=document.querySelector('.contact-grid');if(!grid)return;
    const t=contactLabels[code]||contactLabels.en;
    const cards=[
      {icon:'fa-solid fa-phone',title:t.call,text:'+91 8376882879',href:'tel:+918376882879'},
      {icon:'fa-brands fa-whatsapp',title:t.whatsapp,text:'+91 8376882879',href:'https://wa.me/918376882879',external:true},
      {icon:'fa-solid fa-envelope',title:t.email,text:'manavsolszzz@gmail.com',href:'mailto:manavsolszzz@gmail.com'},
      {icon:'fa-brands fa-linkedin',title:t.linkedin,text:t.founder,href:'https://www.linkedin.com/in/manav-singh-36948a344',external:true},
      {icon:'fa-brands fa-github',title:t.github,text:t.projects,href:'https://github.com/Manav9910ms',external:true},
      {icon:'fa-brands fa-instagram',title:t.instagram,text:t.brand,href:'https://www.instagram.com/manavsols',external:true},
      {icon:'fa-brands fa-youtube',title:t.youtube,text:t.content,href:'https://youtube.com/@manavsols',external:true},
      {icon:'fa-solid fa-bullhorn',title:t.channel,text:t.updates,href:'https://whatsapp.com/channel/0029Vb7ShMvCsU9KsGbjdP30',external:true}
    ];
    grid.replaceChildren(...cards.map(c=>{const a=document.createElement('a');a.className='contact-card';a.href=c.href;if(c.external){a.target='_blank';a.rel='noopener noreferrer'}const i=document.createElement('i');i.className=c.icon;i.setAttribute('aria-hidden','true');const h=document.createElement('h3');h.textContent=c.title;const p=document.createElement('p');p.textContent=c.text;a.append(i,h,p);return a}));
  }
  function addLegalLinks(){const footer=document.querySelector('footer');if(!footer)return;let line=footer.querySelector('.legal-footer-links');if(!line){line=document.createElement('p');line.className='footer-link legal-footer-links';footer.appendChild(line)}if(!line.querySelector('a[href="/terms/"]')){const terms=document.createElement('a');terms.href='/terms/';terms.textContent='Terms & Conditions';line.appendChild(terms)}if(!line.querySelector('a[href="/privacy/"]')){const privacy=document.createElement('a');privacy.href='/privacy/';privacy.textContent='Privacy Policy';if(line.textContent.trim())line.appendChild(document.createTextNode(' · '));line.appendChild(privacy)}}
  function add(){const nav=document.querySelector('.navbar');if(!nav)return;if(!document.getElementById('languageBtn')){const tools=document.createElement('div');tools.className='language-tools';tools.innerHTML='<button class="language-button" id="languageBtn" type="button" aria-haspopup="dialog" aria-controls="languageModal" aria-label="Change language"><i class="fa-solid fa-globe" aria-hidden="true"></i><span id="currentLanguageLabel">English</span></button>';nav.appendChild(tools)}if(!document.getElementById('languageModal')){const modal=document.createElement('div');modal.className='language-modal';modal.id='languageModal';modal.setAttribute('aria-hidden','true');modal.innerHTML='<div class="language-backdrop" data-close-language></div><div class="language-dialog" role="dialog" aria-modal="true" aria-labelledby="languageTitle"><button class="language-close" id="languageClose" type="button" aria-label="Close language selector">×</button><div class="language-icon"><i class="fa-solid fa-language" aria-hidden="true"></i></div><h2 id="languageTitle">Choose your language</h2><p id="languageSubtitle">Select a language for the best experience.</p><select id="languageSelect" aria-label="Select language"></select><button class="btn primary language-continue" id="languageContinue" type="button">Continue</button><p class="language-detected" id="languageDetected"></p></div></div>';document.body.appendChild(modal)}}
  function go(code){localStorage.setItem('manavsols-language',code);localStorage.setItem('manavsols-language-selected','1');location.href=languages[code].path}
  function setup(){add();const code=current(),saved=localStorage.getItem('manavsols-language');const suggested=saved&&languages[saved]?saved:detect();if(code==='en'&&/-in$/.test((navigator.language||'').toLowerCase()))localStorage.setItem('manavsols-language','en');const btn=document.getElementById('languageBtn'),label=document.getElementById('currentLanguageLabel'),modal=document.getElementById('languageModal'),sel=document.getElementById('languageSelect'),close=document.getElementById('languageClose'),cont=document.getElementById('languageContinue'),det=document.getElementById('languageDetected');if(label)label.textContent=languages[code].name;if(sel){sel.innerHTML=codes.map(c=>`<option value="${c}">${languages[c].name}</option>`).join('');sel.value=code}function paint(c){const t=texts[c]||texts.en;document.getElementById('languageTitle').textContent=t[0];document.getElementById('languageSubtitle').textContent=t[1];cont.textContent=t[2]}function closeModal(){modal.classList.remove('open');modal.setAttribute('aria-hidden','true');document.body.classList.remove('language-open')}function openModal(initial){modal.classList.add('open');modal.setAttribute('aria-hidden','false');document.body.classList.add('language-open');sel.value=initial||code;paint(sel.value);if(det&&initial)det.textContent=(texts[sel.value]||texts.en)[3]+': '+languages[sel.value].name}if(btn)btn.onclick=()=>openModal(code);if(close)close.onclick=closeModal;if(cont)cont.onclick=()=>go(sel.value);if(sel)sel.onchange=()=>paint(sel.value);document.querySelectorAll('[data-close-language]').forEach(e=>e.onclick=closeModal);document.onkeydown=e=>{if(e.key==='Escape')closeModal()};applySeo(code);syncContactCards(code);addLegalLinks();if(!localStorage.getItem('manavsols-language-selected'))setTimeout(()=>openModal(suggested),450)}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',setup);else setup();
})();